services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: tg_bot

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  tg_bot:
    build: .
    container_name: tg_bot
    restart: always


volumes:
  pgdata:
  redis_data:
